DENY SELECT ON SCHEMA:: [INFORMATION_SCHEMA] TO [deyan]
GO
DENY SELECT ON SCHEMA:: [INFORMATION_SCHEMA] TO [milos]
GO
DENY SELECT ON SCHEMA:: [INFORMATION_SCHEMA] TO [roman]
GO
GRANT SELECT ON SCHEMA:: [INFORMATION_SCHEMA] TO [vsevolod]
GO
