CREATE SCHEMA [WebApp]
AUTHORIZATION [dbo]
GO
GRANT DELETE ON SCHEMA:: [WebApp] TO [katsiaryna]
GO
GRANT UPDATE ON SCHEMA:: [WebApp] TO [katsiaryna]
GO
GRANT DELETE ON SCHEMA:: [WebApp] TO [sergey]
GO
